openapi: 3.0.1
info:
  title: SMS and Bulk SMS APIs
  description: |
    This is a generated connector for [Mitto SMS and Bulk SMS APIs v1](https://docs.mitto.ch/sms-api-reference/) OpenAPI specification.
    Send individual SMS reliably and securely, or send them in bulk. 
    You can choose from different servers to test with based on where you want to send a message to.
  x-ballerina-init-description: >
    The connector initialization requires setting the API credentials. 
  
    Create a [Mitto account](https://docs.mitto.ch) and obtain tokens by following [this guide](https://docs.mitto.ch/sms-api/#authentication).
  x-ballerina-display:
    label: Mitto SMS
    iconPath: "icon.png"
  version: '1'
servers:
  - url: https://rest.mittoapi.net
security:
  - apiKeyAuth: []
paths:
  /sms:
    post:
      operationId: sendSms
      summary: Send an SMS
      description: >-
        Send an SMS for marketing or a one-time password. Support for test
        messages, long messages, A/B testing with reference tags, and different
        languages.
      # parameters:
      #   - name: X-Mitto-API-Key
      #     in: header
      #     description: >-
      #       Your API key. You must include it for every request to send an SMS.
      #       Contact Mitto Support to get set up with one.
      #     schema:
      #       type: string
      #     example: uAGJbTkSuUJEMBExuofFwOzqJ5f5biwz1
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              required:
                - from
                - to
                - text
              properties:
                test:
                  type: boolean
                  description: >
                    When set to true, the API call is in test mode and no actual
                    SMS is delivered. The response returns “test”: true. For
                    test calls, there is no id parameter in the response. When
                    set to false, you make the API call in production mode. The
                    system delivers an SMS, and returns the id parameter in the
                    response.
                      If you do not use this parameter , by default you make the API call in production mode.
                  example: true
                from:
                  type: string
                  description: >
                    Free-form text with which the sender identifies themselves
                    to the recipient. This is what the recipient will see as
                    from whom the message is. Can be a phone number, or the name
                    of the company or the service. NOTE - what you provide here
                    may not be shown to the customer depending on how carriers
                    choose to handle your message.
                  example: MITTO SMS
                to:
                  type: string
                  description: >
                    The number to which the message is sent. Numbers are
                    specified in E.164 format. 
                  example: '359898876737'
                text:
                  type: string
                  description: |
                    The body of the SMS message.
                      If the message contains characters outside the range of the GSM Standard and Extended tables, then you need to set the character encoding to Unicode (type=Unicode as a query parameter). For details, refer to Long SMSs and Changing the Default Encoding of the Message. 
                  example: >-
                    Due to the limitations of GSM/PDU standard, the body text of
                    an SMS message cannot be longer than 160 characters (70
                    characters if the text is Unicode format). MITTOs SMS API
                    overcomes this limitations by splitting larger messages into
                    several smaller messages, each of which conforms to that
                    standards. This operation is automatic and you do not have
                    to do anything when making the API request the process is
                    triggered automatically when the text entered in body of the
                    SMS (the body parameter of the request) exceeds the limit.
                type:
                  type: string
                  description: >
                    Character set in which the message body will be encoded. If
                    not specified, the default encoding (GSM) is used. For
                    Unicode, set type Unicode. For Binary, set type to be Byte.
                    For automatic detection set type to auto.
                  example: unicode
                reference:
                  type: string
                  description: >
                    First metadata field for tagging the message. The metadata
                    is returned in the delivery report by the callback. It can
                    be any free-form text you consider appropriate. You can use
                    a different reference string for each message or tag
                    multiple messages with the same string and group them
                    together in this way. For details, refer to [Delivery
                    Reports](https://docs.mitto.ch/sms-use-cases/#retrieve-delivery-reports)
                    and [Add Metadata to the
                    Message](https://docs.mitto.ch/sms-use-cases/#add-metadata-to-a-message).
                  example: Spring campaign
                udh:
                  type: string
                  description: |
                    Custom Hex-encoded User Data Header.
                  example: 6050415811581
                validity:
                  type: integer
                  description: >
                    Validity period of the SMS message in minutes. When a
                    message has not been delivered to the receiver at the first
                    attempt, subsequent delivery attempts will be made until the
                    validity period expires, after which the message is
                    discarded as undeliverable. If the specified validity period
                    is different from the validity period of the supplier, then
                    the shorter period is enforced. When not specified, the
                    validity of a message defaults to 2,880 minutes (48 hours).
                  example: 2879
                pid:
                  type: integer
                  description: >
                    Protocol identifier to use. Must be consistent with the udh
                    parameter value. When not specified, defaults to 0.
                flash:
                  type: boolean
                  description: >
                    When set to true it will send the message in Flash mode.
                    Flash SMS is when the SMS appears directly on the main
                    screen without user interaction, and is not automatically
                    stored in the inbox.
                  example: true
                callback:
                  type: string
                  description: >
                    When used, it overrides the URL address set on the account.
                    For more details see the use case [Replace Callback URL in
                    API
                    Call](http://mitto.wpengine.com/sms-use-cases/#optional-callback-url-in-api-call).
                  example: https://www.mycallback.com
            examples:
              Make a Test API Call:
                value:
                  from: MITTO SMS
                  to: '15555552795'
                  text: Hello, World!
                  test: true
              Send an SMS:
                value:
                  from: MITTO SMS
                  to: '15555552795'
                  text: Hello, World!
              Send a Long SMS:
                value:
                  from: MITTO SMS
                  to: '491725551234'
                  text: >-
                    Due to the limitations of GSM/PDU standard, the body text of
                    an SMS message cannot be longer than 160 characters (70
                    characters if the text is Unicode format). MITTO's SMS API
                    overcomes this limitations by splitting larger messages into
                    several smaller messages, each of which conforms to that
                    standards. This operation is automatic and you don't have to
                    do anything when making the API request the process is
                    triggered automatically when the text entered in body of the
                    SMS (the body parameter of the request) exceeds the limit.
                  type: auto
              Send a Message in a Different Language:
                value:
                  from: MITTO SMS
                  to: '491725551234'
                  text: Здравствуй, Мир!
                  type: auto
              Add Metadata to a Message:
                value:
                  from: MITTO SMS
                  to: '491725551234'
                  text: Enjoy the stunning Spring 2019 visuals in our gallery!
                  reference: Campaign 2019-05, B-split message
      responses:
        '200':
          description: Success.
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/sms'
              examples:
                Response to Test SMS:
                  description: This is a test.
                  value:
                    id: 7d35863fe6f44695a713d54e6ba0aeb5
                    timestamp: '2019-04-13T17:51:06.3091182Z'
                    responseCode: 0
                    textLength: 13
                    responseText: SMS sent
                    test: true
                Response to Send SMS:
                  value:
                    id: 715118ef01aa4480bbd67324a0459b0b
                    timestamp: '2019-04-13T12:07:57.8625574Z'
                    to: '41751231234'
                    responseCode: 0
                    textLength: 13
                    responseText: SMS sent
                Response to Send a Long SMS:
                  value:
                    id: 7d35863fe6f44695a713d54e6ba0aeb5
                    timestamp: '2019-04-14T16:55:56.2652450Z'
                    responseCode: 0
                    textLength: 529
                    responseText: SMS sent successfully.
                Response to Send SMS in Another Language:
                  value:
                    id: 715118ef01aa4480bbd67324a0459b0b
                    timestamp: '2019-04-13T12:07:57.8625574Z'
                    responseCode: 0
                    textLength: 13
                    responseText: SMS sent successfully
        '400':
          description: 'Bad Request - '
      servers:
        - url: https://rest.mittoapi.net
    servers:
      - url: https://rest.mittoapi.net
  /sms/converted:
    post:
      operationId: trackConversions
      summary: Track Conversions
      description: >-
        Ask your account manager to enable this feature for you. You can use
        conversion tracking to monitor whether a message was delivered.
      # parameters:
      #   - name: X-Mitto-API-Key
      #     in: header
      #     schema:
      #       type: string
      #     example: uAGJbTkSuUJEMBExuofFwOzqJ5f5biwz
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                messageId:
                  type: string
            examples:
              Conversion Example:
                value: |-
                  {
                  "messageId": "069d0e82-a437-47bc-b158-0f4065e83fce"
                  }
      responses:
        '200':
          description: Success
          # content:
          #   application/json; charset=utf-8:
          #     schema:
          #       $ref: '#/components/schemas/smsconverted'
          #     example: OK
        '400':
          description: >-
            Bad Request - Conversion rate tracking is not enabled for this
            customer account – a JSON string is also returned.
          # content:
          #   application/json; charset=utf-8:
          #     schema:
          #       $ref: '#/components/schemas/badrequest'
          #     example: >-
          #       No convertible message found for id
          #       "8d19cf53-a264-4cc6-800c-95600aeb9141"
        '404':
          description: >-
            Not Found - No message with the given messageId was found to mark as
            converted – a JSON string is also returned.
          # content:
          #   application/json; charset=utf-8:
          #     schema:
          #       $ref: '#/components/schemas/notfound'
          #     example: >-
          #       No convertible message found for id
          #       "8d19cf53-a264-4cc6-800c-95600aeb9141"
        '429':
          description: Too many requests - Too many requests within a certain time frame.
        '500':
          description: Internal Server Error
      servers:
        - url: https://rest.mittoapi.net
    servers:
      - url: https://rest.mittoapi.net
  /smsbulk:
    post:
      operationId: sendBulkSms
      summary: Send SMS in Bulk
      # parameters:
      #   - name: X-Mitto-API-Key
      #     in: header
      #     schema:
      #       type: string
      #     example: uAGJbTkSuUJEMBExuofFwOzqJ5f5biwz
      description: >
        Send multiple messages with a single API call. (If you inlude the same
        phone number in the list more than once, the number will receive a text
        message for each instance in your list.) The response you receive for
        your request will show a different id for each phone number you included
        with your request.
          in: header
          description: 'Your API key. You must include it for every request to send an SMS. Contact Mitto Support to get set up with one.'
          schema:
            type: string
          example: 'uAGJbTkSuUJEMBExuofFwOzqJ5f5biwz'
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              required:
                - from
                - to
                - text
              properties:
                test:
                  type: boolean
                  description: >
                    When set to true, the API call is in test mode and no actual
                    SMSes are delivered. The response returns “test”: true. For
                    test calls, there is no id parameter in the response. When
                    set to false, you make the API call in production mode. The
                    system delivers an SMS, and returns the id parameter in the
                    response.
                      If you do not use this parameter , by default you make the API call in production mode.
                  example: true
                from:
                  type: string
                  description: >
                    Free-form text with which the sender identifies themselves
                    to the recipient. This is what the recipient will see as
                    from whom the message is. Can be a phone number, or the name
                    of the company or the service. NOTE - what you provide here
                    may not be shown to the customer depending on how carriers
                    choose to handle your message.
                  example: MITTO SMS
                to:
                  type: string
                  description: >
                    A list of strings separated by commas. Each string is the
                    number to which your message is sent. Numbers are specified
                    in E.164 format. You can repeat the same phone number, and
                    the message will be sent to the number as many times as the
                    number is listed.
                  example: '359898876737'
                text:
                  type: string
                  description: |
                    The body of the SMS message.
                      If the message contains characters outside the range of the GSM Standard and Extended tables, then you need to set the character encoding to Unicode (type=Unicode as a query parameter). For details, refer to Long SMSs and Changing the Default Encoding of the Message. 
                  example: >-
                    Due to the limitations of GSM/PDU standard, the body text of
                    an SMS message cannot be longer than 160 characters (70
                    characters if the text is Unicode format). MITTOs SMS API
                    overcomes this limitations by splitting larger messages into
                    several smaller messages, each of which conforms to that
                    standards. This operation is automatic and you do not have
                    to do anything when making the API request the process is
                    triggered automatically when the text entered in body of the
                    SMS (the body parameter of the request) exceeds the limit.
                type:
                  type: string
                  description: >
                    Character set in which the message body will be encoded. If
                    not specified, the default encoding (GSM) is used. For
                    Unicode, set type Unicode. For Binary, set type to be Byte.
                    For automatic detection set type to auto.
                  example: unicode
                reference:
                  type: string
                  description: >
                    First metadata field for tagging the message. The metadata
                    is returned in the delivery report by the callback. It can
                    be any free-form text you consider appropriate. You can use
                    a different reference string for each message or tag
                    multiple messages with the same string and group them
                    together in this way.
                  example: Spring campaign
                udh:
                  type: string
                  description: |
                    Custom Hex-encoded User Data Header.
                  example: 6050415811581
                validity:
                  type: integer
                  description: >
                    Validity period of the SMS message in minutes. When a
                    message has not been delivered to the receiver at the first
                    attempt, subsequent delivery attempts will be made until the
                    validity period expires, after which the message is
                    discarded as undeliverable. If the specified validity period
                    is different from the validity period of the supplier, then
                    the shorter period is enforced. When not specified, the
                    validity of a message defaults to 2,880 minutes (48 hours).
                  example: 2879
                pid:
                  type: integer
                  description: >
                    Protocol identifier to use. Must be consistent with the udh
                    parameter value. When not specified, defaults to 0.
                flash:
                  type: boolean
                  description: >
                    When set to true it will send the message in Flash mode.
                    Flash SMS is when the SMS appears directly on the main
                    screen without user interaction, and is not automatically
                    stored in the inbox.
                  example: true
                callback:
                  type: string
                  description: |
                    When used, it overrides the URL address set on the account. 
                  example: https://www.mycallback.com
      responses:
        '200':
          description: Success.
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/smsbulk'
              examples: {}
      servers:
        - url: https://rest.mittoapi.net
    servers:
      - url: https://rest.mittoapi.net
  /usage/bycountry:
    post:
      operationId: getUsageByCountry
      summary: Usage by Country
      description: Find out how much you are using the API per country.
      # parameters:
      #   - name: X-Mitto-API-Key
      #     in: header
      #     schema:
      #       type: string
      #     example: uAGJbTkSuUJEMBExuofFwOzqJ5f5biwz
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              required:
                - startDate
                - endDate
                - accountName
              properties:
                startDate:
                  type: string
                  description: >
                    The date you want to start retrieving usage retrieving usage
                    information from. The date should be expressed according to
                    ISO-8601 format YYYY-MM-DD or YYYYMMDD.
                  example: '2020-02-15'
                endDate:
                  type: string
                  description: >
                    The date you want to stop retrieving usage information from.
                    As with the start date, use ISO-8601 format YYYY-MM-DD or
                    YYYYMMDD.
                  example: '2020-02-28'
                accountName:
                  type: string
                  description: >
                    The account name tied to your API key. If unknown, please
                    contact your Account Manager.
                  example: Starfleet Academy
      responses:
        '200':
          description: Success.
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/usage'
components:
  schemas:
    usage:
      type: object
      title: Usage
      properties:
        country:
          type: string
          description: >
            The country code expressed according to [ISO 3166-1
            Alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1) code format.
        messagesCount:
          type: string
          description: |
            Number of messages sent per country.
        cost:
          type: string
          description: >
            This is the account name tied to your API key. If unknown, please
            contact your account manager at Mitto for more information.
    sms:
      type: object
      title: SMS
      properties:
        id:
          type: string
          description: >-
            ID string of the SMS message. When the length of the body text of
            the message exceeds the limit, then several concatenated are send to
            the receiver and in that case only id of the first message is
            returned. Not returned when making a test call or when error occurs.
        timestamp:
          type: string
          description: >-
            Timestamp of the SMS message in ISO 8601 format. Example -
            2019-04-13T17:51:06.3091182Z For a description of the format, refer
            to [Date and Time Formats](https://www.w3.org/TR/NOTE-datetime) page
            of the W3 Consortium.
        responseCode:
          type: integer
          description: >-
            Text describing the responseCode. For details, refer to Status
            Codes.
        textLength:
          type: integer
          description: >-
            The length of the message you sent. If there is an error, or if the
            message is empty, this will be 0.
        responseText:
          type: string
          description: >-
            Text describing the responseCode. For details, refer to Status
            Codes.
        test:
          type: boolean
          description: >-
            When "test" is set to true, it indicates you are making a test API
            call. (No actual SMS is sent.) When not present, or when "test" is
            set to false or not included, an actual message is sent.
      example:
        id: 7d35863fe6f44695a713d54e6ba0aeb5
        timestamp: '2019-04-13T17:51:06.3091182Z'
        responseCode: 0
        textLength: 13
        responseText: SMS sent
        test: true
    smsbulk:
      type: object
      title: smsbulk
      properties:
        responseCode:
          type: integer
        responseText:
          type: string
        messages:
          type: object
          properties:
            id:
              type: string
              description: >-
                The unique identifier for the individual message sent to a phone
                number.
            timestamp:
              type: string
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      name: X-Mitto-API-Key
      in: header
      description: Represents API Key `X-Mitto-API-Key`
