openapi: 3.0.0
info:
  x-ballerina-display:
    label: Chaingateway
    iconPath: "icon.png"
  title: Chaingateway.io
  description: |-
    This is a generated connector for [Chaingateway API v1.0](https://chaingateway.io/docs-ethereum) OpenAPI specification.
    This is the REST API to build the bridge between Ethereum and the real world. 
    All of the integrations communicates with chaingateway.io through this API.
  contact: {}
  version: '1.0'
  x-ballerina-init-description: >
    The connector initialization requires setting the API credentials.
    
    Create an [Chaingateway.io Account](https://chaingateway.io/register) and obtain tokens following [this guide](https://chaingateway.io/docs-ethereum#apikey).
servers:
  - url: 'https://eu.eth.chaingateway.io/v1'
    variables: {}
paths:
  /getToken:
    post:
      tags:
        - Info Requests
      summary: Returns information about a specific ERC20 token like name, symbol, decimal places and total supply.
      description: Returns information about a specific ERC20 token like name, symbol, decimal places and total supply.
      operationId: getToken
      requestBody:
        description: Payload to get a details about ERC20 token like name, symbol, decimal places and total supply
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getTokenRequest'
            example:
              contractaddress: '0x5b86a33f0c232fe909eb4602a9d039072869d915'
        required: true
      responses:
        '200':
          description: Information about a specific ERC20 token like name, symbol, decimal places and total supply
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getToken'
              example:
                ok: true
                contractaddress: '0x5b86a33f0c232fe909eb4602a9d039072869d915'
                name: Bitfranken
                symbol: BIFRA
                decimals: 2
                supply: 76507131570
      deprecated: false
      security: 
        - api-key: []
  /getLastBlockNumber:
    post:
      tags:
        - Info Requests
      summary: Returns the block number of the last mined Ethereum block.
      description: Returns the block number of the last mined Ethereum block.
      operationId: getLastBlockNumber
      parameters:
        - name: Content-Type
          description: Result of content type of resuly whether json or xml
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: Block number of the last mined Ethereum block
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getLastBlockNumber'
              example:
                ok: true
                blocknumber: 10892021
      deprecated: false
      security: 
        - api-key: []
  /getGasPrice:
    post:
      tags:
        - Info Requests
      summary: Returns the current gas price in GWEI.
      description: Returns the current gas price in GWEI.
      operationId: getGasPrice
      parameters:
        - name: Content-Type
          description: Result of content type of resuly whether json or xml
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: Current gas price in GWEI.
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getGasPrice'
              example:
                ok: true
                gasprice: 70
      deprecated: false
      security: 
        - api-key: []
  /getExchangeRate:
    post:
      tags:
        - Info Requests
      summary: Returns the current Ethereum price in Euro or US Dollar.
      description: Returns the current Ethereum price in Euro or US Dollar.
      operationId: getExchangeRate
      requestBody:
        description: Payload to get current Ethereum price in Euro or US Dollar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getExchangeRateRequest'
            example:
              currency: eur
        required: true
      responses:
        '200':
          description: Current Ethereum price in Euro or US Dollar
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getExchangeRate'
              example:
                ok: true
                currency: eur
                rate: 321.2
      deprecated: false
      security: 
        - api-key: []
  /getEthereumBalance:
    post:
      tags:
        - Info Requests
      summary: Returns the Ethereum balance of a given address.
      description: Returns the Ethereum balance of a given address.
      operationId: getEthereumBalance
      requestBody:
        description: Payload to get Ethereum balance of a given address
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getEthereumBalanceRequest'
            example:
              ethereumaddress: '0xa1f36016221d48ce7f15cde7b826a4fbe09bacce'
        required: true
      responses:
        '200':
          description: Ethereum balance of a given address
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getEthereumBalance'
              example:
                ok: true
                ethereumaddress: '0xa1f36016221d48ce7f15cde7b826a4fbe09bacce'
                balance: 0.009956019840987648
      deprecated: false
      security: 
        - api-key: []
  /getTokenBalance:
    post:
      tags:
        - Info Requests
      summary: Returns the token balance of a given address.
      description: Returns the token balance of a given address.
      operationId: getTokenBalance
      requestBody:
        description: Payload to get token balance of a given address
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getTokenBalanceRequest'
            example:
              contractaddress: '0x5b86a33f0c232fe909eb4602a9d039072869d915'
              ethereumaddress: '0xa1f36016221d48ce7f15cde7b826a4fbe09bacce'
        required: true
      responses:
        '200':
          description: Token balance of a given address
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTokenBalance'
              example:
                ok: true
                contractaddress: '0x5b86a33f0c232fe909eb4602a9d039072869d915'
                ethereumaddress: '0xa1f36016221d48ce7f15cde7b826a4fbe09bacce'
                balance: 9980
      deprecated: false
      security: 
        - api-key: []
  /getTransactions:
    post:
      tags:
        - Info Requests
      summary: Returns information like confirmations, token contract address, amount, gas price and more of a given transaction.
      description: Returns information like confirmations, token contract address, amount, gas price and more of a given transaction.
      operationId: getTransactions
      requestBody:
        description: Payload to get a details about given transaction
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getTransactionsRequest'
            example:
              txid: '0x8ab5543bc103bdd908681da501d03c2c495afd7fde5ed104935ba97b1550d65b'
        required: true
      responses:
        '200':
          description: Information like confirmations, token contract address, amount, gas price and more of a given transaction
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTransactions'
              example:
                ok: true
                transactions:
                  - txid: '0x8ab5543bc103bdd908681da501d03c2c495afd7fde5ed104935ba97b1550d65b'
                    block_number: '6432816'
                    contract_address: '0x9E2B71e87d9304c4773674584EB9D0c838643568'
                    type: ERC20
                    token_name: Shopiblock
                    token_symbol: SHB
                    token_decimals: '18'
                    token_supply: '1000000000'
                    gas: '90000'
                    gas_price: '9'
                    from: '0x8dF9654c7D81c850FDd35D93292B2fC60e666bF0'
                    to: '0xbee9422f1b65687d0cb923bbd1fc5ccb9307e861'
                    amount: '10'
      deprecated: false
      security: 
        - api-key: []
  /getBlock:
    post:
      tags:
        - Info Requests
      summary: Returns information of an Ethereum block with or without transactions.
      description: Returns information of an Ethereum block with or without transactions.
      operationId: getBlock
      requestBody:
        description: Payload to get a Ethereum block
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getBlockRequest'
            example:
              block: '5000000'
        required: true
      responses:
        '200':
          description: Information of an Ethereum block with or without transactions
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getBlock'
              example:
                ok: true
                hash: '0x7d5a4369273c723454ac137f48a4f142b097aa2779464e6505f1b1c5e37b5382'
                block_number: '5000000'
                parent_hash: '0xcae4df80f5862e4321690857eded0d8a40136dafb8155453920bade5bd0c46c0'
                miner: '0xb2930B35844a230f00E51431aCAe96Fe543a0347'
                difficulty: '2546613975853490'
                size_in_bytes: '24017'
                gas_limit: '8000029'
                gas_used: '7994053'
                time_stamp: '2018-01-30 14:41:33'
                transactions_count: '109'
      deprecated: false
      security: 
        - api-key: []
  /newAddress:
    post:
      tags:
        - Address Requests
      summary: Generates a new Ethereum addresses you can use to send or receive funds. Do not lose the password! We can't restore access to an address if you lose it.
      description: Generates a new Ethereum addresses you can use to send or receive funds. Do not lose the password! We can't restore access to an address if you lose it.
      operationId: newAddress
      requestBody:
        description: Payload to create a new Ethereum address
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newAddressRequest'
            example:
              password: padN39QkRA2hJ
        required: true
      responses:
        '200':
          description: Generated new Ethereum addresses you can use to send or receive funds
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/newAddress'
              example:
                ok: true
                ethereumaddress: '0x71892889ed4d79d88ab6ea3783b571b8ece9bef4'
                password: padN39QkRA2hJ
      deprecated: false
      security: 
        - api-key: []
  /deleteAddress:
    post:
      tags:
        - Address Requests
      summary: Deletes an existing Ethereum address. Be careful when using this function.
      description: Deletes an existing Ethereum address. Be careful when using this function.
      operationId: deleteAddress
      requestBody:
        description: Payload to delete an existing Ethereum address
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteAddressRequest'
            example:
              ethereumaddress: '0x71892689ed0d79d88ab6ea3783b571b8ece9bee3'
              password: padN39QkRA2hJ
        required: true
      responses:
        '200':
          description: Detail of Ethereum addresses deleted
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteAddress'
              example:
                ok: true
                ethereumaddress: '0x71892889ed4d79d88ab6ea3783b571b8ece9bef4'
                deleted: true
      deprecated: false
      security: 
        - api-key: []
  /listAddresses:
    post:
      tags:
        - Address Requests
      summary: Returns all Ethereum addresses created with an account.
      description: Returns all Ethereum addresses created with an account.
      operationId: listAddresses
      parameters:
        - name: Content-Type
          description: Result of content type of resuly whether json or xml
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: Ethereum addresses created with an account
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAddresses'
              example:
                ok: true
                addresses:
                  - ethereumaddress: '0x71892889ed4d79d88ab6ea3783b571b8ece9bef4'
      deprecated: false
      security: 
        - api-key: []
  /importAddress:
    post:
      tags:
        - Address Requests
      summary: Imports an existing keystore into system and makes it possible to send transactions from it.
      description: Imports an existing keystore into system and makes it possible to send transactions from it.
      operationId: importAddress
      requestBody:
        description: Payload to import a keystore into system
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/importAddressRequest'
            example:
              filename: UTC--2020-09-19T10-42-26.196Z--71892889ed4d79d88ab6ea3783b571b8ece9bef4
              content:
                version: 3
                id: 85b790ff-408e-42b8-b123-bec9523964dc
                address: 71892889ed4d79d88ab6ea3783b571b8ece9bef4
                crypto:
                  ciphertext: 9d74262517b984f9b0560b8f23b5e3340f7be0f56b70cd91ff445dcaf5b1968f
                  cipherparams:
                    iv: 76e6f2497b9f2a8e024fc752a5418a6d
                  cipher: aes-128-ctr
                  kdf: scrypt
                  kdfparams:
                    dklen: 32
                    salt: d11d996a7cc4bfad730d4c9b9057eff2c0fb3940b5bfc59db62ae218c14a54f4
                    'n': 131072
                    r: 8
                    p: 1
                  mac: dcc342bbbbb8eea97c89b47bafc23de568fc1a48e0bd21ae8d776a95c4704ac9
              password: padN39QkRA2hJ
        required: true
      responses:
        '200':
          description: List of Ethereum addresses created with an account
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/importAddress'
              example:
                ok: true
                ethaddress: '0x71892889ed4d79d88ab6ea3783b571b8ece9bef4'
                filename: UTC--2020-09-19T10-42-26.196Z--71892889ed4d79d88ab6ea3783b571b8ece9bef4
      deprecated: false
      security: 
        - api-key: []
  /exportAddress:
    post:
      tags:
        - Address Requests
      summary: Exports an existing keystore file so you can use it in other wallets.
      description: Exports an existing keystore file so you can use it in other wallets.
      operationId: exportAddress
      requestBody:
        description: Payload to export an existing keystore file
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/exportAddressRequest'
            example:
              ethaddress: '0x71892889ed4d79d88ab6ea3783b571b8ece9bef4'
              password: padN39QkRA2hJ
        required: true
      responses:
        '200':
          description: List of Ethereum addresses created with an account
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exportAddress'
              example:
                ok: true
                filename: UTC--2020-09-19T10-42-26.196Z--71892889ed4d79d88ab6ea3783b571b8ece9bef4
                content: '{''version'':3,''id'':''85b790ff-408e-42b8-b123-bec9523964dc'',''address'':''71892889ed4d79d88ab6ea3783b571b8ece9bef4'',''crypto'':{''ciphertext'':''9d74262517b984f9b0560b8f23b5e3340f7be0f56b70cd91ff445dcaf5b1968f'',''cipherparams'':{''iv'':''76e6f2497b9f2a8e024fc752a5418a6d''},''cipher'':''aes-128-ctr'',''kdf'':''scrypt'',''kdfparams'':{''dklen'':32,''salt'':''d11d996a7cc4bfad730d4c9b9057eff2c0fb3940b5bfc59db62ae218c14a54f4'',''n'':131072,''r'':8,''p'':1},''mac'':''dcc342bbbbb8eea97c89b47bafc23de568fc1a48e0bd21ae8d776a95c4704ac9''}}'
      deprecated: false
      security: 
        - api-key: []
  /subscribeAddress:
    post:
      tags:
        - Subscription/IPN Requests
      summary: Creates a new subscription/IPN for the given address (and contractaddress). You will receive a notification to the given url every time a deposit is received. Unsubscribe the address before sending tokens/ETH from it or you won't get reliable notifications anymore.
      description: Creates a new subscription/IPN for the given address (and contractaddress). You will receive a notification to the given url every time a deposit is received. Unsubscribe the address before sending tokens/ETH from it or you won't get reliable notifications anymore.
      operationId: subscribeAddress
      requestBody:
        description: Payload to create a new subscription/IPN
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/subscribeAddressRequest'
            example:
              ethereumaddress: '0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974'
              contractaddress: '0x514910771af9ca656af840dff83e8264ecf986ca'
              url: 'https://yoururl.com/ipnreceiver.php'
        required: true
      responses:
        '200':
          description: Detail about Ethereum address
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscribeAddress'
              example:
                ok: true
                ethereumaddress: '0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974'
                contractaddress: '0x514910771af9ca656af840dff83e8264ecf986ca'
                url: 'https://yoururl.com/ipnreceiver.php'
      deprecated: false
      security: 
        - api-key: []
  /unsubscribeAddress:
    post:
      tags:
        - Subscription/IPN Requests
      summary: Deletes an existing subscription/IPN for the given address (and contractaddress).
      description: Deletes an existing subscription/IPN for the given address (and contractaddress).
      operationId: unsubscribeAddress
      requestBody:
        description: Payload to delete an existing subscription/IPN
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/unsubscribeAddressRequest'
            example:
              ethereumaddress: '0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974'
              contractaddress: '0x514910771af9ca656af840dff83e8264ecf986ca'
              url: 'https://yoururl.com/ipnreceiver.php'
        required: true
      responses:
        '200':
          description: Detail about Ethereum address
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unsubscribeAddress'
              example:
                ok: true
                ethereumaddress: '0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974'
                contractaddress: '0x514910771af9ca656af840dff83e8264ecf986ca'
                url: 'https://yoururl.com/ipnreceiver.php'
                deleted: true
      deprecated: false
      security: 
        - api-key: []
  /listSubscribedAddresses:
    post:
      tags:
        - Subscription/IPN Requests
      summary: Returns all subscriptions/IPNs created with an account.
      description: Returns all subscriptions/IPNs created with an account.
      operationId: listSubscribedAddresses
      parameters:
        - name: Content-Type
          description: Result of content type of resuly whether json or xml
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: Details about all Ethereum addresses
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listSubscribedAddresses'
              example:
                ok: true
                ipns:
                  - ethereumaddress: '0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974'
                    contractaddress: '0x514910771af9ca656af840dff83e8264ecf986ca'
                    url: 'https://yoururl.com/ipnreceiver.php'
      deprecated: false
      security: 
        - api-key: []
  /listFailedIPNs:
    post:
      tags:
        - Subscription/IPN Requests
      summary: Returns all IPNs that couldn't be sent. Our system tries to send IPNs 10 times until they end up failed.
      description: Returns all IPNs that couldn't be sent. Our system tries to send IPNs 10 times until they end up failed.
      operationId: listFailedIPNs
      parameters:
        - name: Content-Type
          description: Result of content type of resuly whether json or xml
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: List of IPNs that couldn't be sent
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listFailedIPNs'
              example:
                ok: true
                failed_ipns:
                  - id: '17766'
                    timestamp: '2020-09-19 14:33:01'
                    ethereumaddress: '0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974'
                    contractaddress: '0x514910771af9ca656af840dff83e8264ecf986ca'
                    amount: '496588.7771277759'
                    url: 'https://yoururl.com/ipnreceiver.php'
                    action: deposit
      deprecated: false
      security: 
        - api-key: []
  /resendFailedIPN:
    post:
      tags:
        - Subscription/IPN Requests
      summary: Tries to resend a failed IPN.
      description: Tries to resend a failed IPN.
      operationId: resendFailedIPN
      requestBody:
        description: Payload to resend a failed IPN
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/resendFailedIPNRequest'
            example:
              id: 17766
        required: true
      responses:
        '200':
          description: Status of subscriptions/IPNs
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resendFailedIPN'
              example:
                ok: true
                id: 17766
      deprecated: false
      security: 
        - api-key: []
  /sendEthereum:
    post:
      tags:
        - Transaction Requests
      summary: Sends Ethereum from an address controlled by the account to a specified receiver address.
      description: Sends Ethereum from an address controlled by the account to a specified receiver address.
      operationId: sendEthereum
      requestBody:
        description: Payload to send Ethereum transaction from an address
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sendEthereumRequest'
            example:
              from: '0x3a32c4c31fe8d2a89976af5d284a94a040b44aa8'
              to: '0xef4943d727e34280a2efa0b3352dfd61f508ee48'
              password: padN39QkRA2hJ
              amount: 0.01
        required: true
      responses:
        '200':
          description: Detail about Ethereum transaction from an address
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sendEthereum'
              example:
                ok: true
                txid: '0xcff06775098019d18f7bab6a350c18e86f89399db63cbce5269104e6c9a79499'
                from: '0x3a32c4c31fe8d2a89976af5d284a94a040b44aa8'
                to: '0xef4943d727e34280a2efa0b3352dfd61f508ee48'
                amount: '0.010000000000000000'
      deprecated: false
      security: 
        - api-key: []
  /clearAddress:
    post:
      tags:
        - Transaction Requests
      summary: Sends all available Ethereum funds of an address to a specified receiver address.
      description: Sends all available Ethereum funds of an address to a specified receiver address.
      operationId: clearAddress
      requestBody:
        description: Payload to send all available Ethereum funds from an address
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/clearAddressRequest'
            example:
              ethereumaddress: '0x3a32c4c31fe8d2a89976af5d284a94a040b44aa8'
              newaddress: '0xef4943d727e34280a2efa0b3352dfd61f508ee48'
              password: padN39QkRA2hJ
        required: true
      responses:
        '200':
          description: Detail about all available Ethereum funds from an address
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/clearAddress'
              example:
                ok: true
                txid: '0xcff06775098019d18f7bab6a350c18e86f89399db63cbce5269104e6c9a79499'
                ethereumaddress: '0x3a32c4c31fe8d2a89976af5d284a94a040b44aa8'
                newaddress: '0xef4943d727e34280a2efa0b3352dfd61f508ee48'
                amount: 0.02300916225
                gas: 0.0025199999999999997
                total: '0.025529162250000000'
      deprecated: false
      security: 
        - api-key: []
  /sendToken:
    post:
      tags:
        - Transaction Requests
      summary: Sends ERC20 tokens from an address controlled by the account to a specified receiver address. The token contract address is needed to specify the token. The use of the identifier parameter is recommend and awaits an unique string. Whenever a transaction is beeing sent, the identifier is checked and the transaction gets dropped if there is one with that identifier already.
      description: Sends ERC20 tokens from an address controlled by the account to a specified receiver address. The token contract address is needed to specify the token. The use of the identifier parameter is recommend and awaits an unique string. Whenever a transaction is beeing sent, the identifier is checked and the transaction gets dropped if there is one with that identifier already.
      operationId: sendToken
      requestBody:
        description: Payload to sends ERC20 tokens from an address
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sendTokenRequest'
            example:
              contractaddress: '0xdac17f958d2ee523a2206206994597c13d831ec7'
              from: '0x3a32c4c31fe8d2a89976af5d284a94a040b44aa8'
              to: '0xef4943d727e34280a2efa0b3352dfd61f508ee48'
              password: padN39QkRA2hJ
              amount: 5
              identifier: CN562
        required: true
      responses:
        '200':
          description: Detail about ERC20 tokens transaction
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sendToken'
              example:
                ok: true
                identifier: CN562
                txid: '0xcff06775098019d18f7bab6a350c18e86f89399db63cbce5269104e6c9a79499'
                contractaddress: '0xdac17f958d2ee523a2206206994597c13d831ec7'
                from: '0x3a32c4c31fe8d2a89976af5d284a94a040b44aa8'
                to: '0xef4943d727e34280a2efa0b3352dfd61f508ee48'
                amount: 5
      deprecated: false
      security: 
        - api-key: []
components:
  schemas:
    getTokenRequest:
      title: getTokenRequest
      required:
        - contractaddress
      type: object
      properties:
        contractaddress:
          type: string
      example:
        contractaddress: '0x5b86a33f0c232fe909eb4602a9d039072869d915'
    getToken:
      title: getToken
      required:
        - ok
        - contractaddress
        - name
        - symbol
        - decimals
        - supply
      type: object
      properties:
        ok:
          type: boolean
        contractaddress:
          type: string
        name:
          type: string
        symbol:
          type: string
        decimals:
          type: integer
          format: int32
        supply:
          type: integer
          format: int64
      example:
        ok: true
        contractaddress: '0x5b86a33f0c232fe909eb4602a9d039072869d915'
        name: Bitfranken
        symbol: BIFRA
        decimals: 2
        supply: 76507131570
    getLastBlockNumber:
      title: getLastBlockNumber
      required:
        - ok
        - blocknumber
      type: object
      properties:
        ok:
          type: boolean
        blocknumber:
          type: integer
          format: int32
      example:
        ok: true
        blocknumber: 10892021
    getGasPrice:
      title: getGasPrice
      required:
        - ok
        - gasprice
      type: object
      properties:
        ok:
          type: boolean
        gasprice:
          type: integer
          format: int32
      example:
        ok: true
        gasprice: 70
    getExchangeRateRequest:
      title: getExchangeRateRequest
      required:
        - currency
      type: object
      properties:
        currency:
          type: string
      example:
        currency: eur
    getExchangeRate:
      title: getExchangeRate
      required:
        - ok
        - currency
        - rate
      type: object
      properties:
        ok:
          type: boolean
        currency:
          type: string
        rate:
          type: number
      example:
        ok: true
        currency: eur
        rate: 321.2
    getEthereumBalanceRequest:
      title: getEthereumBalanceRequest
      required:
        - ethereumaddress
      type: object
      properties:
        ethereumaddress:
          type: string
      example:
        ethereumaddress: '0xa1f36016221d48ce7f15cde7b826a4fbe09bacce'
    getEthereumBalance:
      title: getEthereumBalance
      required:
        - ok
        - ethereumaddress
        - balance
      type: object
      properties:
        ok:
          type: boolean
        ethereumaddress:
          type: string
        balance:
          type: number
      example:
        ok: true
        ethereumaddress: '0xa1f36016221d48ce7f15cde7b826a4fbe09bacce'
        balance: 0.009956019840987648
    getTokenBalanceRequest:
      title: getTokenBalanceRequest
      required:
        - contractaddress
        - ethereumaddress
      type: object
      properties:
        contractaddress:
          type: string
        ethereumaddress:
          type: string
      example:
        contractaddress: '0x5b86a33f0c232fe909eb4602a9d039072869d915'
        ethereumaddress: '0xa1f36016221d48ce7f15cde7b826a4fbe09bacce'
    getTokenBalance:
      title: getTokenBalance
      required:
        - ok
        - contractaddress
        - ethereumaddress
        - balance
      type: object
      properties:
        ok:
          type: boolean
        contractaddress:
          type: string
        ethereumaddress:
          type: string
        balance:
          type: integer
          format: int32
      example:
        ok: true
        contractaddress: '0x5b86a33f0c232fe909eb4602a9d039072869d915'
        ethereumaddress: '0xa1f36016221d48ce7f15cde7b826a4fbe09bacce'
        balance: 9980
    getTransactionsRequest:
      title: getTransactionsRequest
      required:
        - txid
      type: object
      properties:
        txid:
          type: string
      example:
        txid: '0x8ab5543bc103bdd908681da501d03c2c495afd7fde5ed104935ba97b1550d65b'
    getTransactions:
      title: getTransactions
      required:
        - ok
        - transactions
      type: object
      properties:
        ok:
          type: boolean
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
      example:
        ok: true
        transactions:
          - txid: '0x8ab5543bc103bdd908681da501d03c2c495afd7fde5ed104935ba97b1550d65b'
            block_number: '6432816'
            contract_address: '0x9E2B71e87d9304c4773674584EB9D0c838643568'
            type: ERC20
            token_name: Shopiblock
            token_symbol: SHB
            token_decimals: '18'
            token_supply: '1000000000'
            gas: '90000'
            gas_price: '9'
            from: '0x8dF9654c7D81c850FDd35D93292B2fC60e666bF0'
            to: '0xbee9422f1b65687d0cb923bbd1fc5ccb9307e861'
            amount: '10'
    Transaction:
      title: Transaction
      required:
        - txid
        - block_number
        - contract_address
        - type
        - token_name
        - token_symbol
        - token_decimals
        - token_supply
        - gas
        - gas_price
        - from
        - to
        - amount
      type: object
      properties:
        txid:
          type: string
        block_number:
          type: string
        contract_address:
          type: string
        type:
          type: string
        token_name:
          type: string
        token_symbol:
          type: string
        token_decimals:
          type: string
        token_supply:
          type: string
        gas:
          type: string
        gas_price:
          type: string
        from:
          type: string
        to:
          type: string
        amount:
          type: string
      example:
        txid: '0x8ab5543bc103bdd908681da501d03c2c495afd7fde5ed104935ba97b1550d65b'
        block_number: '6432816'
        contract_address: '0x9E2B71e87d9304c4773674584EB9D0c838643568'
        type: ERC20
        token_name: Shopiblock
        token_symbol: SHB
        token_decimals: '18'
        token_supply: '1000000000'
        gas: '90000'
        gas_price: '9'
        from: '0x8dF9654c7D81c850FDd35D93292B2fC60e666bF0'
        to: '0xbee9422f1b65687d0cb923bbd1fc5ccb9307e861'
        amount: '10'
    getBlockRequest:
      title: getBlockRequest
      required:
        - block
      type: object
      properties:
        block:
          type: string
      example:
        block: '5000000'
    getBlock:
      title: getBlock
      required:
        - ok
        - hash
        - block_number
        - parent_hash
        - miner
        - difficulty
        - size_in_bytes
        - gas_limit
        - gas_used
        - time_stamp
        - transactions_count
      type: object
      properties:
        ok:
          type: boolean
        hash:
          type: string
        block_number:
          type: string
        parent_hash:
          type: string
        miner:
          type: string
        difficulty:
          type: string
        size_in_bytes:
          type: string
        gas_limit:
          type: string
        gas_used:
          type: string
        time_stamp:
          type: string
        transactions_count:
          type: string
      example:
        ok: true
        hash: '0x7d5a4369273c723454ac137f48a4f142b097aa2779464e6505f1b1c5e37b5382'
        block_number: '5000000'
        parent_hash: '0xcae4df80f5862e4321690857eded0d8a40136dafb8155453920bade5bd0c46c0'
        miner: '0xb2930B35844a230f00E51431aCAe96Fe543a0347'
        difficulty: '2546613975853490'
        size_in_bytes: '24017'
        gas_limit: '8000029'
        gas_used: '7994053'
        time_stamp: '2018-01-30 14:41:33'
        transactions_count: '109'
    newAddressRequest:
      title: newAddressRequest
      required:
        - password
      type: object
      properties:
        password:
          type: string
      example:
        password: padN39QkRA2hJ
    newAddress:
      title: newAddress
      required:
        - ok
        - ethereumaddress
        - password
      type: object
      properties:
        ok:
          type: boolean
        ethereumaddress:
          type: string
        password:
          type: string
      example:
        ok: true
        ethereumaddress: '0x71892889ed4d79d88ab6ea3783b571b8ece9bef4'
        password: padN39QkRA2hJ
    deleteAddressRequest:
      title: deleteAddressRequest
      required:
        - ethereumaddress
        - password
      type: object
      properties:
        ethereumaddress:
          type: string
        password:
          type: string
      example:
        ethereumaddress: '0x71892689ed0d79d88ab6ea3783b571b8ece9bee3'
        password: padN39QkRA2hJ
    deleteAddress:
      title: deleteAddress
      required:
        - ok
        - ethereumaddress
        - deleted
      type: object
      properties:
        ok:
          type: boolean
        ethereumaddress:
          type: string
        deleted:
          type: boolean
      example:
        ok: true
        ethereumaddress: '0x71892889ed4d79d88ab6ea3783b571b8ece9bef4'
        deleted: true
    listAddresses:
      title: listAddresses
      required:
        - ok
        - addresses
      type: object
      properties:
        ok:
          type: boolean
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
      example:
        ok: true
        addresses:
          - ethereumaddress: '0x71892889ed4d79d88ab6ea3783b571b8ece9bef4'
    Address:
      title: Address
      required:
        - ethereumaddress
      type: object
      properties:
        ethereumaddress:
          type: string
      example:
        ethereumaddress: '0x71892889ed4d79d88ab6ea3783b571b8ece9bef4'
    importAddressRequest:
      title: importAddressRequest
      required:
        - filename
        - content
        - password
      type: object
      properties:
        filename:
          type: string
        content:
          $ref: '#/components/schemas/Content'
        password:
          type: string
      example:
        filename: UTC--2020-09-19T10-42-26.196Z--71892889ed4d79d88ab6ea3783b571b8ece9bef4
        content:
          version: 3
          id: 85b790ff-408e-42b8-b123-bec9523964dc
          address: 71892889ed4d79d88ab6ea3783b571b8ece9bef4
          crypto:
            ciphertext: 9d74262517b984f9b0560b8f23b5e3340f7be0f56b70cd91ff445dcaf5b1968f
            cipherparams:
              iv: 76e6f2497b9f2a8e024fc752a5418a6d
            cipher: aes-128-ctr
            kdf: scrypt
            kdfparams:
              dklen: 32
              salt: d11d996a7cc4bfad730d4c9b9057eff2c0fb3940b5bfc59db62ae218c14a54f4
              'n': 131072
              r: 8
              p: 1
            mac: dcc342bbbbb8eea97c89b47bafc23de568fc1a48e0bd21ae8d776a95c4704ac9
        password: padN39QkRA2hJ
    Content:
      title: Content
      required:
        - version
        - id
        - address
        - crypto
      type: object
      properties:
        version:
          type: integer
          format: int32
        id:
          type: string
        address:
          type: string
        crypto:
          $ref: '#/components/schemas/Crypto'
      example:
        version: 3
        id: 85b790ff-408e-42b8-b123-bec9523964dc
        address: 71892889ed4d79d88ab6ea3783b571b8ece9bef4
        crypto:
          ciphertext: 9d74262517b984f9b0560b8f23b5e3340f7be0f56b70cd91ff445dcaf5b1968f
          cipherparams:
            iv: 76e6f2497b9f2a8e024fc752a5418a6d
          cipher: aes-128-ctr
          kdf: scrypt
          kdfparams:
            dklen: 32
            salt: d11d996a7cc4bfad730d4c9b9057eff2c0fb3940b5bfc59db62ae218c14a54f4
            'n': 131072
            r: 8
            p: 1
          mac: dcc342bbbbb8eea97c89b47bafc23de568fc1a48e0bd21ae8d776a95c4704ac9
    Crypto:
      title: Crypto
      required:
        - ciphertext
        - cipherparams
        - cipher
        - kdf
        - kdfparams
        - mac
      type: object
      properties:
        ciphertext:
          type: string
        cipherparams:
          $ref: '#/components/schemas/Cipherparams'
        cipher:
          type: string
        kdf:
          type: string
        kdfparams:
          $ref: '#/components/schemas/Kdfparams'
        mac:
          type: string
      example:
        ciphertext: 9d74262517b984f9b0560b8f23b5e3340f7be0f56b70cd91ff445dcaf5b1968f
        cipherparams:
          iv: 76e6f2497b9f2a8e024fc752a5418a6d
        cipher: aes-128-ctr
        kdf: scrypt
        kdfparams:
          dklen: 32
          salt: d11d996a7cc4bfad730d4c9b9057eff2c0fb3940b5bfc59db62ae218c14a54f4
          'n': 131072
          r: 8
          p: 1
        mac: dcc342bbbbb8eea97c89b47bafc23de568fc1a48e0bd21ae8d776a95c4704ac9
    Cipherparams:
      title: Cipherparams
      required:
        - iv
      type: object
      properties:
        iv:
          type: string
      example:
        iv: 76e6f2497b9f2a8e024fc752a5418a6d
    Kdfparams:
      title: Kdfparams
      required:
        - dklen
        - salt
        - 'n'
        - r
        - p
      type: object
      properties:
        dklen:
          type: integer
          format: int32
        salt:
          type: string
        'n':
          type: integer
          format: int32
        r:
          type: integer
          format: int32
        p:
          type: integer
          format: int32
      example:
        dklen: 32
        salt: d11d996a7cc4bfad730d4c9b9057eff2c0fb3940b5bfc59db62ae218c14a54f4
        'n': 131072
        r: 8
        p: 1
    importAddress:
      title: importAddress
      required:
        - ok
        - ethaddress
        - filename
      type: object
      properties:
        ok:
          type: boolean
        ethaddress:
          type: string
        filename:
          type: string
      example:
        ok: true
        ethaddress: '0x71892889ed4d79d88ab6ea3783b571b8ece9bef4'
        filename: UTC--2020-09-19T10-42-26.196Z--71892889ed4d79d88ab6ea3783b571b8ece9bef4
    exportAddressRequest:
      title: exportAddressRequest
      required:
        - ethaddress
        - password
      type: object
      properties:
        ethaddress:
          type: string
        password:
          type: string
      example:
        ethaddress: '0x71892889ed4d79d88ab6ea3783b571b8ece9bef4'
        password: padN39QkRA2hJ
    exportAddress:
      title: exportAddress
      required:
        - ok
        - filename
        - content
      type: object
      properties:
        ok:
          type: boolean
        filename:
          type: string
        content:
          type: string
      example:
        ok: true
        filename: UTC--2020-09-19T10-42-26.196Z--71892889ed4d79d88ab6ea3783b571b8ece9bef4
        content: '{''version'':3,''id'':''85b790ff-408e-42b8-b123-bec9523964dc'',''address'':''71892889ed4d79d88ab6ea3783b571b8ece9bef4'',''crypto'':{''ciphertext'':''9d74262517b984f9b0560b8f23b5e3340f7be0f56b70cd91ff445dcaf5b1968f'',''cipherparams'':{''iv'':''76e6f2497b9f2a8e024fc752a5418a6d''},''cipher'':''aes-128-ctr'',''kdf'':''scrypt'',''kdfparams'':{''dklen'':32,''salt'':''d11d996a7cc4bfad730d4c9b9057eff2c0fb3940b5bfc59db62ae218c14a54f4'',''n'':131072,''r'':8,''p'':1},''mac'':''dcc342bbbbb8eea97c89b47bafc23de568fc1a48e0bd21ae8d776a95c4704ac9''}}'
    subscribeAddressRequest:
      title: subscribeAddressRequest
      required:
        - ethereumaddress
        - contractaddress
        - url
      type: object
      properties:
        ethereumaddress:
          type: string
        contractaddress:
          type: string
        url:
          type: string
      example:
        ethereumaddress: '0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974'
        contractaddress: '0x514910771af9ca656af840dff83e8264ecf986ca'
        url: 'https://yoururl.com/ipnreceiver.php'
    subscribeAddress:
      title: subscribeAddress
      required:
        - ok
        - ethereumaddress
        - contractaddress
        - url
      type: object
      properties:
        ok:
          type: boolean
        ethereumaddress:
          type: string
        contractaddress:
          type: string
        url:
          type: string
      example:
        ok: true
        ethereumaddress: '0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974'
        contractaddress: '0x514910771af9ca656af840dff83e8264ecf986ca'
        url: 'https://yoururl.com/ipnreceiver.php'
    unsubscribeAddressRequest:
      title: unsubscribeAddressRequest
      required:
        - ethereumaddress
        - contractaddress
        - url
      type: object
      properties:
        ethereumaddress:
          type: string
        contractaddress:
          type: string
        url:
          type: string
      example:
        ethereumaddress: '0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974'
        contractaddress: '0x514910771af9ca656af840dff83e8264ecf986ca'
        url: 'https://yoururl.com/ipnreceiver.php'
    unsubscribeAddress:
      title: unsubscribeAddress
      required:
        - ok
        - ethereumaddress
        - contractaddress
        - url
        - deleted
      type: object
      properties:
        ok:
          type: boolean
        ethereumaddress:
          type: string
        contractaddress:
          type: string
        url:
          type: string
        deleted:
          type: boolean
      example:
        ok: true
        ethereumaddress: '0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974'
        contractaddress: '0x514910771af9ca656af840dff83e8264ecf986ca'
        url: 'https://yoururl.com/ipnreceiver.php'
        deleted: true
    listSubscribedAddresses:
      title: listSubscribedAddresses
      required:
        - ok
        - ipns
      type: object
      properties:
        ok:
          type: boolean
        ipns:
          type: array
          items:
            $ref: '#/components/schemas/Ipn'
      example:
        ok: true
        ipns:
          - ethereumaddress: '0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974'
            contractaddress: '0x514910771af9ca656af840dff83e8264ecf986ca'
            url: 'https://yoururl.com/ipnreceiver.php'
    Ipn:
      title: Ipn
      required:
        - ethereumaddress
        - contractaddress
        - url
      type: object
      properties:
        ethereumaddress:
          type: string
        contractaddress:
          type: string
        url:
          type: string
      example:
        ethereumaddress: '0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974'
        contractaddress: '0x514910771af9ca656af840dff83e8264ecf986ca'
        url: 'https://yoururl.com/ipnreceiver.php'
    listFailedIPNs:
      title: listFailedIPNs
      required:
        - ok
        - failed_ipns
      type: object
      properties:
        ok:
          type: boolean
        failed_ipns:
          type: array
          items:
            $ref: '#/components/schemas/FailedIpn'
      example:
        ok: true
        failed_ipns:
          - id: '17766'
            timestamp: '2020-09-19 14:33:01'
            ethereumaddress: '0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974'
            contractaddress: '0x514910771af9ca656af840dff83e8264ecf986ca'
            amount: '496588.7771277759'
            url: 'https://yoururl.com/ipnreceiver.php'
            action: deposit
    FailedIpn:
      title: FailedIpn
      required:
        - id
        - timestamp
        - ethereumaddress
        - contractaddress
        - amount
        - url
        - action
      type: object
      properties:
        id:
          type: string
        timestamp:
          type: string
        ethereumaddress:
          type: string
        contractaddress:
          type: string
        amount:
          type: string
        url:
          type: string
        action:
          type: string
      example:
        id: '17766'
        timestamp: '2020-09-19 14:33:01'
        ethereumaddress: '0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974'
        contractaddress: '0x514910771af9ca656af840dff83e8264ecf986ca'
        amount: '496588.7771277759'
        url: 'https://yoururl.com/ipnreceiver.php'
        action: deposit
    resendFailedIPNRequest:
      title: resendFailedIPNRequest
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int32
      example:
        id: 17766
    resendFailedIPN:
      title: resendFailedIPN
      required:
        - ok
        - id
      type: object
      properties:
        ok:
          type: boolean
        id:
          type: integer
          format: int32
      example:
        ok: true
        id: 17766
    sendEthereumRequest:
      title: sendEthereumRequest
      required:
        - from
        - to
        - password
        - amount
      type: object
      properties:
        from:
          type: string
        to:
          type: string
        password:
          type: string
        amount:
          type: number
      example:
        from: '0x3a32c4c31fe8d2a89976af5d284a94a040b44aa8'
        to: '0xef4943d727e34280a2efa0b3352dfd61f508ee48'
        password: padN39QkRA2hJ
        amount: 0.01
    sendEthereum:
      title: sendEthereum
      required:
        - ok
        - txid
        - from
        - to
        - amount
      type: object
      properties:
        ok:
          type: boolean
        txid:
          type: string
        from:
          type: string
        to:
          type: string
        amount:
          type: string
      example:
        ok: true
        txid: '0xcff06775098019d18f7bab6a350c18e86f89399db63cbce5269104e6c9a79499'
        from: '0x3a32c4c31fe8d2a89976af5d284a94a040b44aa8'
        to: '0xef4943d727e34280a2efa0b3352dfd61f508ee48'
        amount: '0.010000000000000000'
    clearAddressRequest:
      title: clearAddressRequest
      required:
        - ethereumaddress
        - newaddress
        - password
      type: object
      properties:
        ethereumaddress:
          type: string
        newaddress:
          type: string
        password:
          type: string
      example:
        ethereumaddress: '0x3a32c4c31fe8d2a89976af5d284a94a040b44aa8'
        newaddress: '0xef4943d727e34280a2efa0b3352dfd61f508ee48'
        password: padN39QkRA2hJ
    clearAddress:
      title: clearAddress
      required:
        - ok
        - txid
        - ethereumaddress
        - newaddress
        - amount
        - gas
        - total
      type: object
      properties:
        ok:
          type: boolean
        txid:
          type: string
        ethereumaddress:
          type: string
        newaddress:
          type: string
        amount:
          type: number
        gas:
          type: number
        total:
          type: string
      example:
        ok: true
        txid: '0xcff06775098019d18f7bab6a350c18e86f89399db63cbce5269104e6c9a79499'
        ethereumaddress: '0x3a32c4c31fe8d2a89976af5d284a94a040b44aa8'
        newaddress: '0xef4943d727e34280a2efa0b3352dfd61f508ee48'
        amount: 0.02300916225
        gas: 0.0025199999999999997
        total: '0.025529162250000000'
    sendTokenRequest:
      title: sendTokenRequest
      required:
        - contractaddress
        - from
        - to
        - password
        - amount
        - identifier
      type: object
      properties:
        contractaddress:
          type: string
        from:
          type: string
        to:
          type: string
        password:
          type: string
        amount:
          type: integer
          format: int32
        identifier:
          type: string
      example:
        contractaddress: '0xdac17f958d2ee523a2206206994597c13d831ec7'
        from: '0x3a32c4c31fe8d2a89976af5d284a94a040b44aa8'
        to: '0xef4943d727e34280a2efa0b3352dfd61f508ee48'
        password: padN39QkRA2hJ
        amount: 5
        identifier: CN562
    sendToken:
      title: sendToken
      required:
        - ok
        - identifier
        - txid
        - contractaddress
        - from
        - to
        - amount
      type: object
      properties:
        ok:
          type: boolean
        identifier:
          type: string
        txid:
          type: string
        contractaddress:
          type: string
        from:
          type: string
        to:
          type: string
        amount:
          type: integer
          format: int32
      example:
        ok: true
        identifier: CN562
        txid: '0xcff06775098019d18f7bab6a350c18e86f89399db63cbce5269104e6c9a79499'
        contractaddress: '0xdac17f958d2ee523a2206206994597c13d831ec7'
        from: '0x3a32c4c31fe8d2a89976af5d284a94a040b44aa8'
        to: '0xef4943d727e34280a2efa0b3352dfd61f508ee48'
        amount: 5
  securitySchemes:
    api-key:
      description: All requests on the chaingateway.io API needs to include an API key. The API key can be provided as part of the query string or as a request header. The name of the API key needs to be `Authorization`
      in: header
      name: Authorization
      type: apiKey
      x-ballerina-apikey-description: "Provide your API key as `Authorization`. Eg: `{\"Authorization\" : \"<your API key>\"}`" 
tags:
  - name: Info Requests
    description: 'Requests that return information on balances, transactions, gas price, exchange rates, ...'
  - name: Address Requests
    description: 'Requests to create, list and delete addresses'
  - name: Subscription/IPN Requests
    description: 'Requests for creating, deleting and listing existing subscriptions'
  - name: Transaction Requests
    description: 'Requests to send Tokens, Ethereum and clear addresses'
